#!/bin/bash
#
# Perform necessary puppet setup steps
# after package is installed.
#

PROGNAME=$(basename $0)
INSTALLER_DIR="/opt/puppet"
PREFIX="/usr"

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

function copy_if_absent
{
  if ! [[ -f $2 ]] ; then
    cp -rfp $1 $2
  fi
}

# rm -f before ln -sf is required for solaris 9
rm -f $PREFIX/bin/puppet
rm -f $PREFIX/bin/facter
rm -f $PREFIX/bin/hiera

ln -sf $INSTALLER_DIR/bin/puppet $PREFIX/bin || error_exit "Cannot link puppet to $PREFIX/bin"
ln -sf $INSTALLER_DIR/bin/facter $PREFIX/bin || error_exit "Cannot link facter to $PREFIX/bin"
ln -sf $INSTALLER_DIR/bin/hiera $PREFIX/bin || error_exit "Cannot link hiera to $PREFIX/bin"

if ! [[ -d /etc/puppet ]] ; then
  ln -sf $INSTALLER_DIR/etc/puppet /etc/puppet || error_exit "Cannot link /etc/puppet"
else
  echo "/etc/puppet already exists.  Will not link."
fi

copy_if_absent $INSTALLER_DIR/etc/init.d/puppet /etc/init.d/puppet
chmod 755 /etc/init.d/puppet

copy_if_absent $INSTALLER_DIR/etc/logrotate.d/puppet /etc/logrotate.d/puppet
copy_if_absent $INSTALLER_DIR/etc/sysconfig/puppet /etc/sysconfig/puppet

echo "Thank you for installing Puppet!"

exit 0
