#!/bin/bash
#
# Perform necessary puppet removal steps
# after package is uninstalled.
#

PREFIX="/usr"

# Clean up binary symlinks if they exist
if [ ! -e /etc/redhat-release -o "x$1" == "x0" ] ; then
  rm -f $PREFIX/bin/puppet
  rm -f $PREFIX/bin/facter
  rm -f $PREFIX/bin/hiera
  rm -f /etc/init.d/puppet
  rm -f /etc/sysconfig/puppet
  rm -f /etc/logrotate.d/puppet
  rm -f /var/run/puppet
fi

if [[ -L /etc/puppet && -d /etc/puppet ]] ; then
  rm -f /etc/puppet
fi

echo "Puppet has been uninstalled!"

exit 0
